-- SELECT DE TODOS OS FILMES COM ANO ANTERIOR A 2000 

SELECT *

FROM FILME
WHERE ANO_FILME < 2000

-- SELECT DE FILMES ENTRE 2005 E 2010

SELECT *
FROM FILME
WHERE ANO_FILME BETWEEN 2005 AND 2010

--SELECT DE FILMES ONDE CONTEM RAMBO NA COLUNA NOME_ORIGINAL_FILME

 SELECT *
 FROm FILME
 Where NOME_ORIGINAL_FILME like '%rambo%'

 --01 - SELECIONAR TODOS OS DIRETORES

 Select *
 from diretor
  
  --02 - SELECIONAR TODOS OS ATORES

select *
from ATOR

--03 - SELECIONAR TODOS OS GENEROS

select *
from GENERO

--04 - SELECIONAR TODOS OS FILMES, EXCLUÍDOS, OU NÃO
select *
from FILME


--05 - SELECIONAR OS DIRETORES EM ORDEM DE NOME 

select NOME_DIRETOR
from DIRETOR
order by NOME_DIRETOR

--06 - SELECIONAR OS ATORES EM ORDEM DE CÓDIGO

select *
from ATOR
order by ID_ATOR

--07 - SELECIONAR OS GENEROS EM ORDEM DECRESCENTE DO NOME

select *
from GENERO
order by NOME_GENERO DESC

--08 - SELECIONAR O ANO, O NOME ORIGINAL, O NOME EM PORTUGUÊS E O CÓDIGO IMDB DOS FILMES

SELECT ANO_FILME, NOME_ORIGINAL_FILME, NOME_FILME, ID_FILME
FROM FILME

--09 - SELECIONAR O NOME ORIGINAL DO FILME, O NOME DO DIRETOR, OS NOMES DOS ATORES E O NOME DOS GÊNEROS

SELECT NOME_ORIGINAL_FILME
from filme  f
join DIRETOR  d
on f.ID_DIRETOR = d.ID_DIRETOR 
join FILME_ATOR fa
 on f.ID_FILME = fa.ID_FILME
 join ATOR a
 on fa.ID_ATOR = a.ID_ATOR
 join FILME_GENERO fg
 on f.ID_FILME = fg.ID_FILME
join GENERO g
on fg.ID_GENERO = g.ID_GENERO

--10 - SELECIONAR TODOS OS GÊNEROS COM AS QUANTIDADES DE FILMES DE CADA UM

select g.NOME_GENERO, count(*)
from GENERO g
join FILME_GENERO fg
on g.ID_GENERO= fg.ID_GENERO 
group by NOME_GENERO

--11 - SELECIONAR TODOS OS ANOS DOS FILMES COM AS QUANTIDADES DE FILMES DE CADA UM, ORDENADO DO ANO MAIS RECENTE PARA O MAIS ANTIGO

SELECT ANO_FILME, count(*)
from FILME
group by ANO_FILME 
order by ANO_FILME desc

--11,5 - SELECIONAR TODOS OS ANOS DOS FILMES, COM AS QUANTIDADES DE FILME DE CADA UM ORDENANDO DO MAIS RECENTE ATÉ O MAIS ANTIGO, SE FORAM LANÇADOS MAIS DE 5 NO ANO

SELECT ANO_FILME, COUNT(*) AS'QUANTIDADE FILMES'
FROM FILME 
GROUP BY ANO_FILME 
HAVING COUNT(*) >5 
ORDER BY ANO_FILME DESC

--12- SELECIONAR TODOS OS FILMES DE ANOS COM MAIS DE 3 FILMES 

SELECT ANO_FILME, COUNT(*) AS'QUANTIDADE FILMES'
FROM FILME 
GROUP BY ANO_FILME 
HAVING COUNT(*) >3

-- 13- SELECIONAR TODOS OS DIRETORES QUE FIZERAM MAIS DE UM FILME

SELECT NOME_DIRETOR, COUNT(*)  AS 'QUANTIDADE DE FILMES'
FROM FILME F
JOIN DIRETOR D
ON F.ID_DIRETOR= D.ID_DIRETOR
GROUP BY NOME_DIRETOR
HAVING COUNT(*) >1

--14 -SELECIONAR TODOS OS FILMES QUE O PERSONAGEM SINESTRO APARECE ( UTILIZANDO JOIN E SUBQUERY )

SELECT NOME_FILME, NOME_PERSONAGEM 
FROM FILME F
JOIN FILME_ATOR FA
ON F.ID_FILME = FA.ID_FILME
WHERE NOME_PERSONAGEM LIKE '%SINESTRO%'

-- SUBQUERY

SELECT NOME_FILME, ID_FILME
FROM FILME 
WHERE ID_FILME IN (SELECT ID_FILME
FROM FILME_ATOR
WHERE NOME_PERSONAGEM LIKE '%SINESTRO%')

-- 15 -SELECIONAR TODOS OS FILMES EM QUE O ATOR JAMES EARL JONES TRABALHOU, RETORNAR TAMBÉM A COLUNA COM NOME DO ATOR
SELECT NOME_FILME, NOME_ATOR 
FROM FILME F
JOIN FILME_ATOR FA
ON F.ID_FILME = FA.ID_FILME
JOIN ATOR A
ON FA.ID_ATOR = A.ID_ATOR
WHERE NOME_ATOR LIKE '%JAMES EARL JONES%'

--16 - SELECIONAR TODOS OS FILMES DE 2012, EXCLUÍDOS, OU NÃO
SELECT *
FROM FILME 
WHERE ANO_FILME = 2012

--17 - SELECIONAR TODOS OS FILMES DO DIRETOR RIDLEY SCOTT. RETORNAR TAMBEM A COLUNA COM O NOME DO DIRETOR
SELECT *
FROM FILME F
JOIN DIRETOR D
ON F.ID_DIRETOR = D.ID_DIRETOR
WHERE NOME_DIRETOR LIKE 'RIDLEY SCOTT'


--18 - SELECIONAR OS NOMES DE TODOS OS ATORES QUE TAMBÉM FORAM DIRETORES EM ALGUM FILME
SELECT NOME_ATOR
FROM FILME F
JOIN FILME_ATOR FA
ON F.ID_FILME = FA.ID_FILME
JOIN ATOR A
ON FA.ID_ATOR = A.ID_ATOR
JOIN DIRETOR D
ON F.ID_DIRETOR = D.ID_DIRETOR
WHERE NOME_ATOR = NOME_DIRETOR


--19 - SELECIONAR OS NOMES DE TODOS OS ATORES QUE FORAM DIRETORES NO MESMO FILME
SELECT NOME_ATOR, NOME_DIRETOR
FROM FILME F
JOIN FILME_ATOR FA
ON F.ID_FILME = FA.ID_FILME
JOIN ATOR A
ON FA.ID_ATOR = A.ID_ATOR
JOIN DIRETOR D
ON F.ID_DIRETOR = D.ID_DIRETOR
WHERE NOME_ATOR = NOME_DIRETOR


--20 - SELECIONAR OS TRÊS DIRETORES QUE FIZERAM MAIS FILMES

SELECT TOP(3) WITH TIES NOME_DIRETOR, COUNT(*) AS QTDE
FROM DIRETOR D
JOIN FILME F
ON D.ID_DIRETOR= F.ID_DIRETOR
GROUP BY NOME_DIRETOR
ORDER BY COUNT(*) DESC







	
--29 - SELECIONAR OS DIRETORES QUE NÃO TEM FILMES ASSOCIADOS

SELECT D.NOME_DIRETOR, F.NOME_FILME
FROM DIRETOR D 
LEFT JOIN FILME F -- PODE USAR RIGHT JOIN, SÓ INVERTER MUDANDO O FROM FILME F E JOIN DIRETOR D.
ON D.ID_DIRETOR = F.ID_DIRETOR
WHERE NOME_FILME IS NULL

--30 - SELECIONAR OS GENEROS QUE NÃO TEM FILMES ASSOCIADOS

SELECT G.NOME_GÊNERO, FG.NOME_FILME
FROM GÊNERO G
LEFT JOIN FILMES_GÊNERO FG 
ON G.ID_GÊNERO.ID = FG.ID_GÊNERO
WHERE NOME_FILME IS NULL

--31 - SELECIONAR OS FILMES DO GENERO ACTION DO ANO 2009 QUE TENHAM SCARLETT JOHANSSON NO ELENCO

SELECT F.NOME_ORIGINAL_FILME
FROM FILME 
INNER JOIN FILME_GENERO FG 
ON F.ID_FILME = FD.ID_FILME
INNER JOIN GENERO G 
ON FG.ID_GENERO = G.ID_GENERO
INNER JOIN FILME_ATOR FA 
ON F.ID_FILME = FA.ID_FILME
INNER JOIN ATOR A
ON FA.ID_ATOR = A.ID_ATOR
WHERE F.ANO_FILME = 2009 AND A.NOME_ATOR = 'SCARLETT JOHANSSON' 
AND NOME_GENERO = 'Action'

--32 - SELECIONAR OS DIRETORES DOS FILMES EM QUE JON FAVREAU ATUOU

SELECT D.NOME_DIRETOR, A.NOME_ATOR, F.NOME_FILME
FROM DIRETOR D 
INNER JOIN FILME F 
ON D.ID_DIRETOR = F.ID_DIRETOR
INNER JOIN FILME_ATOR FA 
ON F.ID_FILME = FA.ID_FILME
INNER JOIN ATOR A 
ON FA.ID_ATOR = A.ID_ATOR
WHERE A.NOME_ATOR = 'JON FAVREAU'

--33 - SELECIONAR OS PERSONAGENS DO ATOR KARL URBAN, EXCLUÍDOS, OU NÃO

SELECT DISTINCT FA.NOME_PERSONAGEM --DISTINCT IGNORA LINHA IGUAIS, TRAZENDO APENAS UMA, FAZENDO UMA DISTINÇÃO.
FROM ATOR A 
INNER JOIN FILME_ATOR FA
ON A.ID_ATOR = FA.ID_ATOR 
INNER JOIN FILME F 
ON FA.ID_FILME = F.ID_FILME 
WHERE A.NOME_ATOR = 'KARL URBAN'

--34 - SELECIONAR OS ATORES QUE FIZERAM PERSONAGENS SEM NOME EM FILMES

SELECT DISTINCT A.NOME_ATOR, FA.NOME_PERSONAGEM
FROM ATOR A 
INNER JOIN FILME_ATOR FA 
ON A.ID_ATOR = FA.ID_ATOR 
INNER JOIN FILME F 
ON FA.ID_FILME = F.ID_FILME
WHERE FA.NOME_PERSONAGEM = ''

--35 - SELECIONAR OS NOMES DOS FILMES EM QUE O ATOR KARL URBAN ATUOU

SELECT F.NOME_ORIGINAL_FILME, A.NOME_ATOR
FROM FILME F
INNER JOIN FILME_ATOR FA 
ON F.ID_FILME = FA.ID_FILME
INNER JOIN ATOR A 
ON FA.ID_ATOR = A.ID_ATOR
WHERE A.NOME_ATOR = 'KARL URBAN'
