				-- SELECT DE TODOS OS FILMES COM ANO ANTERIOR A 2000 

SELECT *

FROM FILME
WHERE ANO_FILME < 2000

-- SELECT DE FILMES ENTRE 2005 E 2010

SELECT *
FROM FILME
WHERE ANO_FILME BETWEEN 2005 AND 2010

--SELECT DE FILMES ONDE CONTEM RAMBO NA COLUNA NOME_ORIGINAL_FILME

 SELECT *
 FROm FILME
 Where NOME_ORIGINAL_FILME like '%rambo%'

 --01 - SELECIONAR TODOS OS DIRETORES

 Select *
 from diretor
  
  --02 - SELECIONAR TODOS OS ATORES

select *
from ATOR

--03 - SELECIONAR TODOS OS GENEROS

select *
from GENERO

--04 - SELECIONAR TODOS OS FILMES, EXCLUÍDOS, OU NÃO
select *
from FILME


--05 - SELECIONAR OS DIRETORES EM ORDEM DE NOME 

select NOME_DIRETOR
from DIRETOR
order by NOME_DIRETOR

--06 - SELECIONAR OS ATORES EM ORDEM DE CÓDIGO

select *
from ATOR
order by ID_ATOR

--07 - SELECIONAR OS GENEROS EM ORDEM DECRESCENTE DO NOME

select *
from GENERO
order by NOME_GENERO DESC

--08 - SELECIONAR O ANO, O NOME ORIGINAL, O NOME EM PORTUGUÊS E O CÓDIGO IMDB DOS FILMES

SELECT ANO_FILME, NOME_ORIGINAL_FILME, NOME_FILME, ID_FILME
FROM FILME

--09 - SELECIONAR O NOME ORIGINAL DO FILME, O NOME DO DIRETOR, OS NOMES DOS ATORES E O NOME DOS GÊNEROS

SELECT NOME_ORIGINAL_FILME
from filme  f
join DIRETOR  d
on f.ID_DIRETOR = d.ID_DIRETOR 
join FILME_ATOR fa
 on f.ID_FILME = fa.ID_FILME
 join ATOR a
 on fa.ID_ATOR = a.ID_ATOR
 join FILME_GENERO fg
 on f.ID_FILME = fg.ID_FILME
join GENERO g
on fg.ID_GENERO = g.ID_GENERO

--10 - SELECIONAR TODOS OS GÊNEROS COM AS QUANTIDADES DE FILMES DE CADA UM

select g.NOME_GENERO, count(*)
from GENERO g
join FILME_GENERO fg
on g.ID_GENERO= fg.ID_GENERO 
group by NOME_GENERO

--11 - SELECIONAR TODOS OS ANOS DOS FILMES COM AS QUANTIDADES DE FILMES DE CADA UM, ORDENADO DO ANO MAIS RECENTE PARA O MAIS ANTIGO

SELECT ANO_FILME, count(*)
from FILME
group by ANO_FILME 
order by ANO_FILME desc

--11,5 - SELECIONAR TODOS OS ANOS DOS FILMES, COM AS QUANTIDADES DE FILME DE CADA UM ORDENANDO DO MAIS RECENTE ATÉ O MAIS ANTIGO, SE FORAM LANÇADOS MAIS DE 5 NO ANO

SELECT ANO_FILME, COUNT(*) AS'QUANTIDADE FILMES'
FROM FILME 
GROUP BY ANO_FILME 
HAVING COUNT(*) >5 
ORDER BY ANO_FILME DESC

--12- SELECIONAR TODOS OS FILMES DE ANOS COM MAIS DE 3 FILMES 

SELECT ANO_FILME, COUNT(*) AS'QUANTIDADE FILMES'
FROM FILME 
GROUP BY ANO_FILME 
HAVING COUNT(*) >3

-- 13- SELECIONAR TODOS OS DIRETORES QUE FIZERAM MAIS DE UM FILME

SELECT NOME_DIRETOR, COUNT(*)  AS 'QUANTIDADE DE FILMES'
FROM FILME F
JOIN DIRETOR D
ON F.ID_DIRETOR= D.ID_DIRETOR
GROUP BY NOME_DIRETOR
HAVING COUNT(*) >1

--14 -SELECIONAR TODOS OS FILMES QUE O PERSONAGEM SINESTRO APARECE ( UTILIZANDO JOIN E SUBQUERY )

SELECT NOME_FILME, NOME_PERSONAGEM 
FROM FILME F
JOIN FILME_ATOR FA
ON F.ID_FILME = FA.ID_FILME
WHERE NOME_PERSONAGEM LIKE '%SINESTRO%'

-- SUBQUERY

SELECT NOME_FILME, ID_FILME
FROM FILME 
WHERE ID_FILME IN (SELECT ID_FILME
FROM FILME_ATOR
WHERE NOME_PERSONAGEM LIKE '%SINESTRO%')

-- 15 -SELECIONAR TODOS OS FILMES EM QUE O ATOR JAMES EARL JONES TRABALHOU, RETORNAR TAMBÉM A COLUNA COM NOME DO ATOR
SELECT NOME_FILME, NOME_ATOR 
FROM FILME F
JOIN FILME_ATOR FA
ON F.ID_FILME = FA.ID_FILME
JOIN ATOR A
ON FA.ID_ATOR = A.ID_ATOR
WHERE NOME_ATOR LIKE '%JAMES EARL JONES%'

--16 - SELECIONAR TODOS OS FILMES DE 2012, EXCLUÍDOS, OU NÃO



--17 - SELECIONAR TODOS OS FILMES DO DIRETOR RIDLEY SCOTT. RETORNAR TAMBEM A COLUNA COM O NOME DO DIRETOR



--18 - SELECIONAR OS NOMES DE TODOS OS ATORES QUE TAMBÉM FORAM DIRETORES EM ALGUM FILME



--19 - SELECIONAR OS NOMES DE TODOS OS ATORES QUE FORAM DIRETORES NO MESMO FILME



--20 - SELECIONAR OS TRÊS DIRETORES QUE FIZERAM MAIS FILMES



--21 - SELECIONAR OS CINCO GÊNEROS COM MENOS FILMES



--22 - SELECIONAR OS GÊNEROS DE TODOS OS FILMES DO ANO QUE TEM A MAIOR QUANTIDADE DE FILMES



--23 - SELECIONAR TODOS OS ATORES QUE TENHAM O MESMO NOME DO PERSONAGEM QUE ENCENARAM NOS FILMES



--24 - SELECIONAR TODOS OS ATORES QUE TENHAM FEITO MAIS DE UM PERSONAGEM NO MESMO FILME



--25 - SELECIONAR OS NOMES ORIGINAIS DE TODOS OS FILMES QUE TENHAM MENOS DE 10 ATORES



--26 - CONTAR QUANTOS FILMES DO DIRETOR JON FAVREAU EXISTEM NO CADASTRO



--27 - CONTAR QUANTOS PERSONAGENS EXISTEM NOS FILMES DO DIRETOR RIDLEY SCOTT



--28 - SELECIONAR QUAIS ATORES FIZERAM FILMES DE ACTION OU CRIME OU THRILLER



--29 - SELECIONAR OS DIRETORES QUE NÃO TEM FILMES ASSOCIADOS



--30 - SELECIONAR OS GENEROS QUE NÃO TEM FILMES ASSOCIADOS


